apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - app-db.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - route.yaml

images:
  - name: rhacs-manager-backend
    newName: ghcr.io/dadav/rhacs-manager-backend
    newTag: latest
  - name: rhacs-manager-frontend
    newName: ghcr.io/dadav/rhacs-manager-frontend
    newTag: latest
