apiVersion: v2
name: rhacs-manager
description: Helm chart for deploying RHACS Manager on OpenShift
type: application
version: 0.2.0
appVersion: "0.19.10"
keywords:
  - rhacs
  - stackrox
  - cve
  - vulnerability-management
  - openshift
home: https://github.com/dadav/rhacs-manager
sources:
  - https://github.com/dadav/rhacs-manager
maintainers:
  - name: dadav
    url: https://github.com/dadav
