{{- if and (eq (default "hub" .Values.mode) "hub") .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  namespace: {{ include "rhacs-manager.namespace" . }}
  labels:
    {{- include "rhacs-manager.labels" . | nindent 4 }}
  {{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
